version: '3.6'
services:
  db:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - flos_part_db
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: backend
      target: dev-envs
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pickle:/pickle
      - ./dbBackup:/dbBackup
    secrets:
      - db-password
    networks:
      - flos_part_db
    depends_on:
      - db

  proxy:
    build: proxy
    restart: always
#    ports:
#      - 8088:80
    depends_on: 
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smdparts-flo.entrypoints=https"
      - "traefik.http.routers.smdparts-flo.rule=Host(`smdparts-flo.energyhosting.at`)" ## Hier eure Domain eingeben ##
      - "traefik.http.routers.smdparts-flo.tls=true"
      - "traefik.http.routers.smdparts-flo.tls.certresolver=http"
      - "traefik.http.routers.smdparts-flo.service=smdparts-flo"
      - "traefik.http.services.smdparts-flo.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - flos_part_db
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart nginx-flask-mysql_backend_1; done"]
    restart: unless-stopped

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  flos_part_db:
    external: true
  web:
    external: true
