version: '3.3'
services:
  db:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
#      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - flos_part_db
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=../run/secrets/db-password
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: ../backend
#      target: dev-envs
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - db-password
    networks:
      - flos_part_db
      - web
    depends_on:
      - db

  proxy:
    build: ../proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smdparts_flo.entrypoints=https"
      - "traefik.http.routers.smdparts_flo.rule=Host(`smdparts_flo.energyhosting.at`)" ## Hier eure Domain eingeben ##
      - "traefik.http.routers.smdparts_flo.tls=true"
      - "traefik.http.routers.smdparts_flo.tls.certresolver=http"
      - "traefik.http.routers.smdparts_flo.service=smdparts_flo"
      - "traefik.http.services.smdparts_flo.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web

volumes:
  db-data:

secrets:
  db-password:
    file: ../db/password.txt

networks:
  flos_part_db:
    external: true
  web:
    external: true
